### PR TITLE
Updated to new remote format

### PR DESCRIPTION
**Pull request by tkhduracell**
Hi,

we're updating for a standard for public remotes. We will soon be able to show all remotes on our website, and we want you to join us in this journey. Remotes should now have icon.png and a higher resolution (max 512x512) image named icon_hires.png. Furthermore, we've added screenshots of each remote to its README.md.

### CODE REVIEW

**Comment by Abrimaal** [comment]
Hi, I have added three "onhold" functions: colour saturation -/+, flip vertical.

**Comment by tkhduracell** [comment]
Okey great, just accept this pull request and you can continue your work. We will link to your repository (Abrimaal/IrfanView-Unified-Remote) in the future.

**Comment by Abrimaal** [comment]
What should I do? Where to click?

**Comment by tkhduracell** [comment]
Follow steps 1-6 here: 
https://help.github.com/articles/merging-a-pull-request/ 

Good luck!

**Comment by Abrimaal** [comment]
I really don't understand it. I can see 1 pull request, but when I select it, "merge" is not active
merge-not-active
Only "new pull request" is active. 

merge
If you can, please merge it. The API is definitely too complicated for a newcomer.

**Comment by tkhduracell** [comment]
Okey, I think I've come up with a solution. I'll create a new one without the conflicts.

**Pull request closed without merging**
